version: '3.8'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 81903
      POSTGRES_DB: sistema_jogos
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
