"""add unique user+game on reviews

Revision ID: 1619612e5533
Revises: f93329ddb2e4
Create Date: 2025-06-10 21:04:35.344296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1619612e5533'
down_revision: Union[str, None] = 'f93329ddb2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_usuario_jogo', 'reviews', ['usuario_id', 'jogo_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usuario_jogo', 'reviews', type_='unique')
    # ### end Alembic commands ###
