"""added more keys for table

Revision ID: 2cb7f9c51997
Revises: d0db5755a3ad
Create Date: 2025-06-11 17:31:59.808742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cb7f9c51997'
down_revision: Union[str, None] = 'd0db5755a3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'families', ['criador_id'])
    op.create_unique_constraint('purchase_usuario_jogo', 'purchase', ['usuario_id', 'jogo_id'])
    op.create_unique_constraint('uq_user_family', 'user_families', ['user_id', 'family_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_family', 'user_families', type_='unique')
    op.drop_constraint('purchase_usuario_jogo', 'purchase', type_='unique')
    op.drop_constraint(None, 'families', type_='unique')
    # ### end Alembic commands ###
