"""added dlc table

Revision ID: b3bbd65f8bee
Revises: 1619612e5533
Create Date: 2025-06-11 17:48:11.417182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3bbd65f8bee'
down_revision: Union[str, None] = '1619612e5533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dlc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_lancamento', sa.Date(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desenvolvedora', sa.String(length=100), nullable=False),
    sa.Column('jogo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jogo_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dlc_id'), 'dlc', ['id'], unique=False)
    op.create_index(op.f('ix_dlc_titulo'), 'dlc', ['titulo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dlc_titulo'), table_name='dlc')
    op.drop_index(op.f('ix_dlc_id'), table_name='dlc')
    op.drop_table('dlc')
    # ### end Alembic commands ###
