"""setting unique constraints

Revision ID: f1ed68c9a6b5
Revises: f5307230b4a8
Create Date: 2025-06-06 16:06:55.389150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1ed68c9a6b5'
down_revision: Union[str, None] = 'f5307230b4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_titulo'), table_name='games')
    op.create_index(op.f('ix_games_titulo'), 'games', ['titulo'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_games_titulo'), table_name='games')
    op.create_index(op.f('ix_games_titulo'), 'games', ['titulo'], unique=False)
    # ### end Alembic commands ###
