"""removing unique values

Revision ID: f5307230b4a8
Revises: 6bbc38a42bae
Create Date: 2025-06-06 10:17:07.644593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5307230b4a8'
down_revision: Union[str, None] = '6bbc38a42bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_titulo'), table_name='games')
    op.create_index(op.f('ix_games_titulo'), 'games', ['titulo'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_games_titulo'), table_name='games')
    op.create_index(op.f('ix_games_titulo'), 'games', ['titulo'], unique=True)
    # ### end Alembic commands ###
