"""create_table_purchase

Revision ID: f93329ddb2e4
Revises: f1ed68c9a6b5
Create Date: 2025-06-09 19:55:45.077341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f93329ddb2e4'
down_revision: Union[str, None] = 'f1ed68c9a6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('jogo_id', sa.Integer(), nullable=False),
    sa.Column('preco_pago', sa.Float(), nullable=False),
    sa.Column('forma_pagamento', sa.Text(), nullable=False),
    sa.Column('data_compra', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['jogo_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_id'), 'purchase', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_id'), table_name='purchase')
    op.drop_table('purchase')
    # ### end Alembic commands ###
