"""added unique to jogo_id field

Revision ID: fd1b516b40fd
Revises: b3bbd65f8bee
Create Date: 2025-06-11 17:54:42.231921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd1b516b40fd'
down_revision: Union[str, None] = 'b3bbd65f8bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dlc', ['jogo_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dlc', type_='unique')
    # ### end Alembic commands ###
